### ISSUE TITLE
Cannot load error after inserting embedded_schema

### ISSUE THREAD

**Issue by bigardone** [bitwalker/timex_ecto#15]
Hello!
I'm not sure if it's an error related to **timex** or **timex_ecto**. The thing is that I've added a **DateTime** field to an Ecto schema. When I try to insert or update it works fine. The problem comes when I try o get the record from the database. I get the following error:

```
** (ArgumentError) cannot load `%{"calendar" => "gregorian", "day" => 5, "hour" => 8, "minute" => 40, "month" => 2, "ms" => 924, "second" => 5, "timezone" => %{"abbreviation" => "UTC", "from" => "min", "full_name" => "UTC", "offset_std" => 0, "offset_utc" => 0, "until" => "max"}, "year" => 2016}` as type Timex.Ecto.DateTime
      (ecto) lib/ecto/schema.ex:982: Ecto.Schema.load!/3
      (ecto) lib/ecto/schema.ex:966: anonymous fn/4 in Ecto.Schema.do_load/4
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
      (ecto) lib/ecto/schema.ex:957: Ecto.Schema.__load__/6
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
      (ecto) lib/ecto/type.ex:459: Ecto.Type.load_embed/3
      (ecto) lib/ecto/schema.ex:980: Ecto.Schema.load!/3
      (ecto) lib/ecto/schema.ex:974: anonymous fn/3 in Ecto.Schema.do_load/4
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
      (ecto) lib/ecto/schema.ex:972: Ecto.Schema.do_load/4
      (ecto) lib/ecto/schema.ex:957: Ecto.Schema.__load__/6
      (ecto) lib/ecto/adapters/sql.ex:519: anonymous fn/3 in Ecto.Adapters.SQL.process_row/3
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
      (ecto) lib/ecto/adapters/sql.ex:513: Ecto.Adapters.SQL.process_row/3
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
      (ecto) lib/ecto/adapters/sql.ex:283: Ecto.Adapters.SQL.decode/2
    (stdlib) timer.erl:166: :timer.tc/1
      (ecto) lib/ecto/adapters/sql.ex:278: Ecto.Adapters.SQL.decode/3
      (ecto) lib/ecto/adapters/sql.ex:225: Ecto.Adapters.SQL.query/5
      (ecto) lib/ecto/adapters/sql.ex:183: Ecto.Adapters.SQL.query!/5
```

These are the current versions I'm using:

```
"timex": {:hex, :timex, "1.0.0"},
"timex_ecto": {:hex, :timex_ecto, "0.7.0"},
```

I think I've followed correctly the instructions, do you think I'm missing anything?

Thanks in advance

**Comment by bigardone** [comment]
Oh! I forgot to mention that the model has a **embeds_many** relationship where I use **DateTime** as well, and it's saving it just like in the error, so it's not transforming it to a valid date format while inserting. Is this an error or is there anything special I have to do in order to use Timex in a **embedded_schema**?

Thank you very much in advance

**Comment by bitwalker** [comment]
@bigardone I'll try and create a simple example to reproduce and go from there. If you can share your schema or one which reproduces the issue, that would be hugely helpful!

**Comment by bigardone** [comment]
Yeah of course! here's the schema:

``` elixir
defmodule HelloPhoenix.TimeEntry do
  use HelloPhoenix.Web, :model
  alias HelloPhoenix.{TimeRange}
  alias Timex.Ecto.DateTime

  schema "time_entries" do
    field :description, :string
    field :started_at, DateTime
    field :stopped_at, DateTime

    embeds_many :ranges, TimeRange

    timestamps
  end
end

defmodule HelloPhoenix.TimeRange do
  use Ecto.Schema
  alias Timex.Ecto.DateTime

  embedded_schema do
    field :start, DateTime
    field :stop, DateTime
    field :duration, :integer
  end
end
```

The error is thrown after getting a `TimeEntry` which has a `TimeRange`.

**Comment by dyerc** [comment]
I have just run into the same issue. If it's any help my schema is:

``` elixir
defmodule MyApp.Notification do
  use Ecto.Schema

  embedded_schema do
    #....
    field :last_sent, Timex.Ecto.DateTime
  end
end

defmodule MyApp.User do
  schema "users" do
    #....
    embeds_many :notifications, MyApp.Notification
  end
end
```

If I try to do the following I get the same error as @bigardone 

``` elixir
    user = Repo.get(User, u.id)
    if user do
      marked_sent = Enum.map(user.notifications, fn(n) ->
        Map.put(n, :last_sent, Date.now)
      end)

      changeset = user
      |> Ecto.Changeset.change
      |> Ecto.Changeset.put_embed(:notifications, marked_sent)

      Repo.update!(changeset)
    end
```

**Comment by bitwalker** [comment]
Thanks to the both of you, I'll take a look now and see if I can't get a fix up today.

**Comment by bitwalker** [comment]
@bigardone @CD1212 This has been fixed in master, a new release will be on hex shortly

**Comment by bigardone** [comment]
Awesome, thank you very much!

**Comment by dyerc** [comment]
Thanks very much, thats fixed it
